#!/usr/bin/env sh
set -o nounset
set -o errexit

# See Generating distribution archives
# https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives
. "$VIRTUAL_ENV"/bin/activate
python -m pip install --upgrade setuptools wheel
python setup.py sdist bdist_wheel --dist-dir "${PYTHON_DIST:-"dist"}"
